const popularDogBreeds = [
    'Akita',
    'Australian Shepherd',
    'Beagle',
    'Bernese Mountain Dog',
    'Bichon Frise',
    'Border Collie',
    'Boston Terrier',
    'Boxer',
    'Bulldog',
    'Cavalier King Charles Spaniel',
    'Chihuahua',
    'Cocker Spaniel',
    'Dachshund',
    'Dalmatian',
    'Doberman Pinscher',
    'French Bulldog',
    'German Shepherd',
    'Golden Retriever',
    'Great Dane',
    'Husky',
    'Labrador Retriever',
    'Maltese',
    'Miniature Schnauzer',
    'Pomeranian',
    'Poodle',
    'Pug',
    'Rottweiler',
    'Shih Tzu',
    'Siberian Husky',
    'Staffordshire Bull Terrier',
    'West Highland White Terrier / Westie',
    'Yorkshire Terrier',
    'Boxer',
    'Basset Hound',
  ].sort();
  
  export default popularDogBreeds;