const sampleData = [
  {
    id: 1,
    name: "Buddy",
    breed: "Golden Retriever",
    age: "Adult",
    size: "Large",
    gender: "Male",
    type: "Dog",
    coat: "Medium",
    description: "Friendly and playful Golden Retriever.",
    photos: [
      "https://photos.petfinder.com/photos/pets/42706540/1/?bust=1546042081&width=600",
    ],
    status: "Adoptable",
    contact: {
      email: "buddyshelter@gmail.com",
      phone: "123-456-7890",
      address: {
        address1: "123 Dog Street",
        address2: "Apt 4B",
        city: "Pawtown",
        state: "CA",
        postcode: "12345",
        country: "US",
      },
    },
    tags: ["Friendly", "Golden Retriever"],
  },
  {
    id: 2,
    name: "Whiskers",
    breed: "Siamese",
    age: "Kitten",
    size: "Small",
    gender: "Female",
    type: "Cat",
    coat: "Short",
    description: "Adorable Siamese kitten looking for a home.",
    photos: [
      "https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg",
    ],
    status: "Adoptable",
    contact: {
      email: "whiskersshelter@gmail.com",
      phone: "987-654-3210",
      address: {
        address1: "456 Cat Lane",
        address2: "Apt 2C",
        city: "Meowville",
        state: "NY",
        postcode: "54321",
        country: "US",
      },
    },
    tags: ["Kitten", "Siamese", "Adorable"],
  },
  {
    id: 3,
    name: "Max",
    breed: "Labrador Retriever",
    age: "Adult",
    size: "Large",
    gender: "Male",
    type: "Dog",
    coat: "Short",
    description: "Loving Labrador Retriever looking for a forever home.",
    photos: [
      "https://photos.petfinder.com/photos/pets/42706540/1/?bust=1546042081&width=600",
    ],
    status: "Adoptable",
    contact: {
      email: "maxshelter@gmail.com",
      phone: "555-123-4567",
      address: {
        address1: "789 Woof Avenue",
        address2: "Unit 3D",
        city: "Dogsville",
        state: "TX",
        postcode: "67890",
        country: "US",
      },
    },
    tags: ["Friendly", "Labrador Retriever", "Loving"],
  },
  {
    id: 4,
    name: "Sasha",
    breed: "Persian",
    age: "Adult",
    size: "Medium",
    gender: "Female",
    type: "Cat",
    coat: "Long",
    description: "Beautiful Persian cat looking for a quiet home.",
    photos: [
      "https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg",
    ],
    status: "Adoptable",
    contact: {
      email: "sashashelter@gmail.com",
      phone: "777-987-6543",
      address: {
        address1: "123 Purr Lane",
        address2: "Apt 1A",
        city: "Purrington",
        state: "CA",
        postcode: "54321",
        country: "US",
      },
    },
    tags: ["Persian", "Beautiful", "Quiet"],
  },
  
  ];
  
export default sampleData;