const sampleData = [
    {
      id: 120,
      name: "Spot a dog",
      breed: "Akita",
      age: "Young",
      size: "Medium",
      gender: "Male",
      type: "Dog",
      coat: null,
      description: "Spot is an amazing dog",
      photos: [
        "https://photos.petfinder.com/photos/pets/42706540/1/?bust=1546042081&width=600",
      ],
      status: "Adoptable",
      contact: {
        email: "petfindertechsupport@gmail.com",
        phone: "111-333-5555, 222-333-5555, 333-333-5353, 111-333-2222",
        address: {
          address1: "Test address 1",
          address2: "Test address 2",
          city: "Jersey City",
          state: "NJ",
          postcode: "07097",
          country: "US",
        },
      },
      tags: ["Cute", "Intelligent", "Large", "Playful", "Happy", "Affectionate"],
    },
    {
      id: 121,
      name: "Niki a cat",
      age: "Young",
      size: "Small",
      gender: "Female",
      type: "Cat",
      coat: null,
      description: "amazing cat",
      photos: [
        "https://photos.petfinder.com/photos/pets/42706540/1/?bust=1546042081&width=600",
      ],
      status: "Adoptable",
      contact: {
        email: "petfindertechsupport@gmail.com",
        phone: "111-333-5555, 222-333-5555, 333-333-5353, 111-333-2222",
        address: {
          address1: "Test address 1",
          address2: "Test address 2",
          city: "Jersey City",
          state: "NJ",
          postcode: "07097",
          country: "US",
        },
      },
      tags: ["Cute", "Intelligent", "Large", "Playful", "Happy", "Affectionate"],
    },
    {
      id: 122,
      name: "Sample Pet 3 a cat",
      breed: "Siamese",
      age: "Kitten",
      size: "Small",
      gender: "Female",
      type: "Cat",
      coat: "Short",
      description: "This is a cute Siamese kitten.",
      photos: ["Placeholder image"],
      status: "Adoptable",
      contact: "Placeholder contact information",
      tags: ["Kitten", "Siamese"],
    },
    {
      id: 123,
      name: "Sample Pet 4 a dog",
      breed: "Golden Retriever",
      age: "Adult",
      size: "Large",
      gender: "Male",
      type: "Dog",
      coat: "Medium",
      description: "Friendly and playful Golden Retriever.",
      photos: ["Placeholder image"],
      status: "Adoptable",
      contact: "Placeholder contact information",
      tags: ["Friendly", "Golden Retriever"],
    },
  ];
  
export default sampleData;