const popularDogBreeds = [
    'Akita',
    'American Bulldog',
    'Australian Shepherd',
    'Basset Hound',
    'Beagle',
    'Bernese Mountain Dog',
    'Bichon Frise',
    'Border Collie',
    'Boston Terrier',
    'Boxer',
    'Bulldog',
    'Cavalier King Charles Spaniel',
    'Cane Corso',
    'Chihuahua',
    'Chiweenie',
    'Cocker Spaniel',
    'Dachshund',
    'Dalmatian',
    'Doberman Pinscher',
    'French Bulldog',
    'German Shepherd',
    'Golden Retriever',
    'Great Dane',
    'Hound',
    'Husky',
    'Labrador Retriever',
    'Maltese',
    'Miniature Schnauzer',
    'Mixed Breed',
    'Pomeranian',
    'Poodle',
    'Pug',
    'Rottweiler',
    'Shepherd',
    'Shih Tzu',
    'Siberian Husky',
    'Staffordshire Bull Terrier',
    'Terrier',
    'West Highland White Terrier / Westie',
    'Whippet',
    'Yellow Labrador Retriever',
    'Yorkshire Terrier',
  ].sort();
  
  export default popularDogBreeds;