/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://gmuw7hc3qjcevj434ywm4m6pda.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-k7zoe2zxt5hxddpojpsgokj2ea",
    "aws_cognito_identity_pool_id": "us-east-1:60347861-a70f-4313-ba7d-ee879400b81a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TLiJm3EJ9",
    "aws_user_pools_web_client_id": "44415flli5q9pvbj3ej8e3f8sa",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "userFavorites-staging",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
